apiVersion: apps/v1
kind: Deployment
metadata:
  name: length-batch-window-distributed-server2-deployment
  labels:
    app: length-batch-window-distributed-server2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: length-batch-window-distributed-server2
  template:
    metadata:
      labels:
        app: length-batch-window-distributed-server2
    spec:
      containers:
      - name: llength-window-server2
        image: suhothayan/siddhitest:latest
        ports:
        - containerPort: 80
        env:
        -
          name: MAIN_CLASS
          value: "org.suho.siddhi.window.lengthBatch.distributed.LengthBatchWindowServer1"
        -
          name: CONSUME
          value: "80"
        -
          name: PUBLISH
          value: "length-batch-window-distributed-unique-server-service:80"
        -
          name: DATA1
          value: "10000"
        -
          name: DATA2
          value: "2"

---
kind: Service
apiVersion: v1
metadata:
  name: length-batch-window-distributed-server2-service
spec:
  selector:
    app: length-batch-window-distributed-server2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80