apiVersion: apps/v1
kind: Deployment
metadata:
  name: length-batch-window-distributed-publisher-deployment
  labels:
    app: length-batch-window-distributed-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: length-batch-window-distributed-publisher
  template:
    metadata:
      labels:
        app: length-batch-window-distributed-publisher
    spec:
      containers:
      - name: length-batch-window-publisher
        image: suhothayan/siddhitest:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        -
          name: MAIN_CLASS
          value: "org.suho.siddhi.window.lengthBatch.distributed.EventPublisher"
        -
          name: CONSUME
          value: "-"
        -
          name: PUBLISH
          value: "length-batch-window-distributed-server1-service:80,length-batch-window-distributed-server2-service:80,length-batch-window-distributed-server3-service:80,length-batch-window-distributed-server4-service:80"
        -
          name: DATA1
          value: "-"
        -
          name: DATA2
          value: "-"