apiVersion: apps/v1
kind: Deployment
metadata:
  name: join-largelarge-distributed-server3-deployment
  labels:
    app: join-largelarge-distributed-server3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: join-largelarge-distributed-server3
  template:
    metadata:
      labels:
        app: join-largelarge-distributed-server3
    spec:
      containers:
      - name: llength-window-server3
        image: suhothayan/siddhitest:latest
        ports:
        - containerPort: 80
        env:
        -
          name: MAIN_CLASS
          value: "org.suho.siddhi.join.largelarge.distributed.JoinServer3"
        -
          name: CONSUME
          value: "80"
        -
          name: PUBLISH
          value: "join-largelarge-distributed-unique-server-service:80"
        -
          name: DATA1
          value: "10000,10000"
        -
          name: DATA2
          value: "3"
---
kind: Service
apiVersion: v1
metadata:
  name: join-largelarge-distributed-server3-service
spec:
  selector:
    app: join-largelarge-distributed-server3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80