apiVersion: apps/v1
kind: Deployment
metadata:
  name: join-smalllarge-distributed-server2-deployment
  labels:
    app: join-smalllarge-distributed-server2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: join-smalllarge-distributed-server2
  template:
    metadata:
      labels:
        app: join-smalllarge-distributed-server2
    spec:
      containers:
      - name: llength-window-server
        image: suhothayan/siddhitest:latest
        ports:
        - containerPort: 80
        env:
        -
          name: MAIN_CLASS
          value: "org.suho.siddhi.join.smalllarge.distributed.JoinServer2"
        -
          name: CONSUME
          value: "80"
        -
          name: PUBLISH
          value: "join-smalllarge-distributed-unique-server-service:80"
        -
          name: DATA1
          value: "10000,150"
        -
          name: DATA2
          value: "2"
---
kind: Service
apiVersion: v1
metadata:
  name: join-smalllarge-distributed-server2-service
spec:
  selector:
    app: join-smalllarge-distributed-server2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80