apiVersion: apps/v1
kind: Deployment
metadata:
  name: length-window-publisher-deployment
  labels:
    app: length-window-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: length-window-publisher
  template:
    metadata:
      labels:
        app: length-window-publisher
    spec:
      containers:
      - name: llength-window-publisher
        image: suhothayan/siddhitest:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        -
          name: MAIN_CLASS
          value: "org.suho.siddhi.window.length.EventPublisher"
        -
          name: CONSUME
          value: "-"
        -
          name: PUBLISH
          value: "length-window-server-service:80"
        -
          name: DATA1
          value: "-"
        -
          name: DATA2
          value: "-"