apiVersion: apps/v1
kind: Deployment
metadata:
  name: pattern-prepartition-distributed-server1-deployment
  labels:
    app: pattern-prepartition-distributed-server1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pattern-prepartition-distributed-server1
  template:
    metadata:
      labels:
        app: pattern-prepartition-distributed-server1
    spec:
      containers:
      - name: llength-window-server1
        image: suhothayan/siddhitest:latest
        ports:
        - containerPort: 80
        env:
        -
          name: MAIN_CLASS
          value: "org.suho.siddhi.pattern.distributed.prepartition.PatternServer1"
        -
          name: CONSUME
          value: "80"
        -
          name: PUBLISH
          value: "pattern-prepartition-distributed-server3-service:80,pattern-prepartition-distributed-server4-service:80"
        -
          name: DATA1
          value: "1 min"
        -
          name: DATA2
          value: "60000"
---
kind: Service
apiVersion: v1
metadata:
  name: pattern-prepartition-distributed-server1-service
spec:
  selector:
    app: pattern-prepartition-distributed-server1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80