apiVersion: apps/v1
kind: Deployment
metadata:
  name: length-batch-window-publisher-deployment
  labels:
    app: length-batch-window-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: length-batch-window-publisher
  template:
    metadata:
      labels:
        app: length-batch-window-publisher
    spec:
      containers:
      - name: llength-window-publisher
        image: suhothayan/siddhitest:latest
        ports:
        - containerPort: 80
        env:
        -
          name: MAIN_CLASS
          value: "org.suho.siddhi.window.lengthBatch.EventPublisher"
        -
          name: CONSUME
          value: "-"
        -
          name: PUBLISH
          value: "length-batch-window-server-service:80"
        -
          name: DATA1
          value: "-"
        -
          name: DATA2
          value: "-"