apiVersion: apps/v1
kind: Deployment
metadata:
  name: pattern-prepartition-distributed-server1-deployment
  labels:
    app: pattern-prepartition-distributed-server1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pattern-prepartition-distributed-server1
  template:
    metadata:
      labels:
        app: pattern-prepartition-distributed-server1
    spec:
      containers:
      - name: pattern-prepartition-distributed-server1
        image: suhothayan/siddhitest:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        -
          name: MAIN_CLASS
          value: "org.suho.siddhi.pattern.distributed.prepartition.PatternServer1"
        -
          name: CONSUME
          value: "80"
        -
          name: PUBLISH
          value: "pattern-prepartition-distributed-server3-service:80,pattern-prepartition-distributed-server4-service:80,pattern-prepartition-distributed-server41-service:80,pattern-prepartition-distributed-server42-service:80"
        -
          name: DATA1
          value: "5 min"
        -
          name: DATA2
          value: "300000"
        -
          name: JAVA_OPPS
          value: "-Xms128m -Xmx256m"
---
kind: Service
apiVersion: v1
metadata:
  name: pattern-prepartition-distributed-server1-service
spec:
  selector:
    app: pattern-prepartition-distributed-server1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80