apiVersion: apps/v1
kind: Deployment
metadata:
  name: join-smalllarge-server-deployment
  labels:
    app: join-smalllarge-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: join-smalllarge-server
  template:
    metadata:
      labels:
        app: join-smalllarge-server
    spec:
      containers:
      - name: join-smalllarge-server
        image: suhothayan/siddhitest:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
        env:
        -
          name: MAIN_CLASS
          value: "org.suho.siddhi.join.smalllarge.JoinServer"
        -
          name: CONSUME
          value: "80"
        -
          name: PUBLISH
          value: "join-smalllarge-consumer-service:80"
        -
          name: DATA1
          value: "60"
        -
          name: DATA2
          value: "20"
        -
          name: JAVA_OPPS
          value: ""
---
kind: Service
apiVersion: v1
metadata:
  name: join-smalllarge-server-service
spec:
  selector:
    app: join-smalllarge-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80