apiVersion: apps/v1
kind: Deployment
metadata:
  name: pattern-broadcast-distributed-server2-deployment
  labels:
    app: pattern-broadcast-distributed-server2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pattern-broadcast-distributed-server2
  template:
    metadata:
      labels:
        app: pattern-broadcast-distributed-server2
    spec:
      containers:
      - name: pattern-broadcast-distributed-server2
        image: suhothayan/siddhitest:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        -
          name: MAIN_CLASS
          value: "org.suho.siddhi.pattern.distributed.broadcast.PatternServer2"
        -
          name: CONSUME
          value: "80"
        -
          name: PUBLISH
          value: "pattern-broadcast-distributed-server3-service:80"
        -
          name: DATA1
          value: "4 min"
        -
          name: DATA2
          value: "240000"
        -
          name: JAVA_OPPS
          value: "-Xms128m -Xmx256m"
---
kind: Service
apiVersion: v1
metadata:
  name: pattern-broadcast-distributed-server2-service
spec:
  selector:
    app: pattern-broadcast-distributed-server2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80